# Generated by Django 3.1.7 on 2021-03-09 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('krw', '0002_auto_20210309_0814'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiscordUser',
        ),
    ]
